#!/bin/bash
# ==================================================
# This file is managed by SaltStack certbot formula.
# Manual changes may be overwritten.
# ==================================================
#
# Run certbot in a container
#
# This script will attempt to mirror the host paths by using volumes for the
# following paths:
#   * {{ conf_dir }}
#
# You can add additional volumes (or any docker run options) using
# the $CERTBOT_OPTIONS environment variable.
#


set -e

IMAGE=${IMAGE:-"{{ image }}"}
CONF_DIR=${CONF_DIR:-"{{ conf_dir }}"}

if [ -d "$CONF_DIR" ]; then
    VOLUMES="-v $CONF_DIR:$CONF_DIR"
fi

# Only allocate tty if we detect one
if [ -t 1 ]; then
    DOCKER_RUN_OPTIONS="-t"
fi
if [ -t 0 ]; then
    DOCKER_RUN_OPTIONS="$DOCKER_RUN_OPTIONS -i"
fi

exec docker run --rm $DOCKER_RUN_OPTIONS --network host $CERTBOT_OPTIONS $VOLUMES $IMAGE certbot "$@"
